Feature add pull listings close by
TheReallyGreatTeamFSEMarch2021/airTNB pull request #19
Opened 2021-04-21 14:17 UTC by FeiYGH

2021-04-21 14:54 UTC, Eliotdoesprogramming requested changes
Lets discuss a little bit after stand ups before merging

2021-04-21 14:54 UTC, Eliotdoesprogramming commented on src/main/java/com/talentpath/airTNB/controllers/ListingController.java
> +        System.out.println("HEY DOUBLE CHECKING");
Remove debugging prints before merging to staging

2021-04-21 14:54 UTC, Eliotdoesprogramming commented on src/main/java/com/talentpath/airTNB/models/Listing.java
>      private String state;
City and State should be tied to location, would like to talk through the logic of separating them

2021-04-21 14:54 UTC, Eliotdoesprogramming commented on src/main/java/com/talentpath/airTNB/services/ListingService.java
> +        String city, state;
String city and state are never used, can be assigned and refactored to

String city = listing.get().getCity();
String state = listing.get().getState();
listingRepository.findAllByCityIgnoreCaseAndStateIgnoreCase(city,state);

2021-04-21 14:54 UTC, Eliotdoesprogramming commented on src/main/java/com/talentpath/airTNB/controllers/ListingController.java
> +        return listingService.getListingsByCityAndState(listingId);
Likely want to refactor at this level to parse city and state, instead of sending the method an ID.

2021-04-22 18:14 UTC, Eliotdoesprogramming approved these changes
Looks good, good job with creating the query for lat and longitude!

2021-04-22 19:20 UTC, mattfreshwaters approved these changes
lgtm! tested just fine

2021-04-22 19:44 UTC, merged